#!/bin/bash

echo "TRAVIS_BRANCH $TRAVIS_BRANCH"
echo "JAVA_HOME $JAVA_HOME"
echo "TRAVIS_EVENT_TYPE $TRAVIS_EVENT_TYPE"
echo "TRAVIS_JOB_NAME $TRAVIS_JOB_NAME"
echo "TRAVIS_PULL_REQUEST $TRAVIS_PULL_REQUEST"
echo "TRAVIS_BUILD_NUMBER $TRAVIS_BUILD_NUMBER"
echo "TRAVIS_BUILD_STAGE_NAME $TRAVIS_BUILD_STAGE_NAME"
echo "TRAVIS_JDK_VERSION $TRAVIS_JDK_VERSION"
echi "JDK_SWITCHER_DEFAULT $JDK_SWITCHER_DEFAULT"


if[ $TRAVIS_JDK_VERSION = $JDK_SWITCHER_DEFAULT ]
then 
    echo "JAVA8"
else 
    echo "NOT JAVA8"
fi
