//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.24 at 07:57:06 PM BST 
//


package com.github.nexus.config.api;

import java.nio.file.Path;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.github.nexus.config.jaxb.PathAdapter;


/**
 * <p>Java class for PublicKey complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicKey"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="path" type="{http://nexus.github.com/config/api}Path"/&gt;
 *           &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicKey", propOrder = {
    "path",
    "value"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-24T07:57:06+01:00", comments = "JAXB RI v2.2.11")
public class PublicKey
    implements com.github.nexus.config.PublicKey
{

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(PathAdapter.class)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-24T07:57:06+01:00", comments = "JAXB RI v2.2.11")
    protected Path path;
    @XmlSchemaType(name = "anyURI")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-24T07:57:06+01:00", comments = "JAXB RI v2.2.11")
    protected String value;

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-24T07:57:06+01:00", comments = "JAXB RI v2.2.11")
    public Path getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-24T07:57:06+01:00", comments = "JAXB RI v2.2.11")
    public void setPath(Path value) {
        this.path = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-24T07:57:06+01:00", comments = "JAXB RI v2.2.11")
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2018-06-24T07:57:06+01:00", comments = "JAXB RI v2.2.11")
    public void setValue(String value) {
        this.value = value;
    }

}
