CREATE TABLE ENCRYPTED_TRANSACTION (ENCODED_PAYLOAD LONGVARBINARY NOT NULL, PAYLOAD_CODEC VARCHAR, TIMESTAMP BIGINT, HASH LONGVARBINARY NOT NULL, PRIMARY KEY (HASH));
CREATE TABLE ENCRYPTED_RAW_TRANSACTION (PAYLOAD_CODEC VARCHAR NOT NULL, ENCRYPTED_KEY LONGVARBINARY NOT NULL, ENCRYPTED_PAYLOAD LONGVARBINARY NOT NULL, NONCE LONGVARBINARY NOT NULL, SENDER LONGVARBINARY NOT NULL, TIMESTAMP BIGINT, HASH LONGVARBINARY NOT NULL, PRIMARY KEY (HASH));
CREATE TABLE PRIVACY_GROUP (ID LONGVARBINARY NOT NULL, DATA LONGVARBINARY NOT NULL, LOOKUP_ID LONGVARBINARY, TIMESTAMP BIGINT, PRIMARY KEY (ID));
CREATE INDEX PRIVACY_GROUP_LOOKUPID ON PRIVACY_GROUP (LOOKUP_ID);
CREATE TABLE ST_TRANSACTION (ID BIGINT NOT NULL, PAYLOAD_CODEC VARCHAR NOT NULL, HASH VARCHAR NOT NULL, PAYLOAD LONGVARBINARY, PRIVACY_MODE INTEGER, TIMESTAMP BIGINT, VALIDATION_STAGE BIGINT, PRIMARY KEY (ID));
CREATE INDEX ST_TRANSACTION_VALSTG ON ST_TRANSACTION (VALIDATION_STAGE);
CREATE INDEX ST_TRANSACTION_HASH ON ST_TRANSACTION (HASH);
CREATE TABLE ST_AFFECTED_TRANSACTION (ID BIGINT NOT NULL, AFFECTED_HASH VARCHAR NOT NULL, TXN_ID BIGINT NOT NULL, PRIMARY KEY (ID));
ALTER TABLE ST_AFFECTED_TRANSACTION ADD CONSTRAINT FK_ST_AFFECTED_TRANSACTION_TXN_ID FOREIGN KEY (TXN_ID) REFERENCES ST_TRANSACTION (ID);

