CREATE TABLE ENCRYPTED_TRANSACTION (ENCODED_PAYLOAD LONGVARBINARY NOT NULL, TIMESTAMP BIGINT, HASH LONGVARBINARY NOT NULL, PRIMARY KEY (HASH));
CREATE TABLE ENCRYPTED_RAW_TRANSACTION (ENCRYPTED_KEY LONGVARBINARY NOT NULL, ENCRYPTED_PAYLOAD LONGVARBINARY NOT NULL, NONCE LONGVARBINARY NOT NULL, SENDER LONGVARBINARY NOT NULL, TIMESTAMP BIGINT, HASH LONGVARBINARY NOT NULL, PRIMARY KEY (HASH));
CREATE TABLE PRIVACY_GROUP(ID LONGVARBINARY NOT NULL, LOOKUP_ID LONGVARBINARY NOT NULL, DATA LONGVARBINARY NOT NULL, TIMESTAMP BIGINT, PRIMARY KEY (ID));
