CREATE TABLE ENCRYPTED_TRANSACTION (ENCODED_PAYLOAD BYTEA NOT NULL, HASH BYTEA NOT NULL, TIMESTAMP DECIMAL(19), PRIMARY KEY (HASH));
CREATE TABLE ENCRYPTED_RAW_TRANSACTION (ENCRYPTED_KEY BYTEA NOT NULL, ENCRYPTED_PAYLOAD BYTEA NOT NULL, NONCE BYTEA NOT NULL, SENDER BYTEA NOT NULL, TIMESTAMP DECIMAL(19), HASH BYTEA NOT NULL, PRIMARY KEY (HASH));
CREATE TABLE PRIVACY_GROUP(ID BYTEA NOT NULL, LOOKUP_ID BYTEA NOT NULL, DATA BYTEA NOT NULL, TIMESTAMP DECIMAL(19), PRIMARY KEY (ID));
