CREATE TABLE ENCRYPTED_TRANSACTION (ENCODED_PAYLOAD BYTEA NOT NULL, PAYLOAD_CODEC VARCHAR(50), HASH BYTEA NOT NULL, TIMESTAMP DECIMAL(19), PRIMARY KEY (HASH));
CREATE TABLE ENCRYPTED_RAW_TRANSACTION (ENCRYPTED_KEY BYTEA NOT NULL, ENCRYPTED_PAYLOAD BYTEA NOT NULL, NONCE BYTEA NOT NULL, SENDER BYTEA NOT NULL, TIMESTAMP DECIMAL(19), HASH BYTEA NOT NULL, PRIMARY KEY (HASH));
CREATE TABLE PRIVACY_GROUP(ID BYTEA NOT NULL, LOOKUP_ID BYTEA NOT NULL, DATA BYTEA NOT NULL, TIMESTAMP DECIMAL(19), PRIMARY KEY (ID));
CREATE TABLE ST_TRANSACTION(ID BIGINT NOT NULL CONSTRAINT ST_TRANSACTION_PKEY PRIMARY KEY, PAYLOAD_CODEC VARCHAR(50), HASH VARCHAR(255) NOT NULL, PAYLOAD BYTEA, PRIVACY_MODE INTEGER, TIMESTAMP BIGINT,VALIDATION_STAGE BIGINT);
CREATE TABLE ST_AFFECTED_TRANSACTION(ID BIGINT NOT NULL CONSTRAINT ST_AFFECTED_TRANSACTION_PKEY PRIMARY KEY, AFFECTED_HASH VARCHAR(255) NOT NULL, TXN_ID BIGINT NOT NULL CONSTRAINT FK_ST_AFFECTED_TRANSACTION_TXN_ID REFERENCES ST_TRANSACTION);
CREATE INDEX IF NOT EXISTS ST_TRANSACTION_VALSTG ON ST_TRANSACTION (VALIDATION_STAGE);
