CREATE TABLE ENCRYPTED_TRANSACTION (ENCODED_PAYLOAD BLOB NOT NULL, PAYLOAD_CODEC VARCHAR(50) NOT NULL, TIMESTAMP NUMBER(19), HASH BLOB NOT NULL, PRIMARY KEY (HASH));
CREATE TABLE ENCRYPTED_RAW_TRANSACTION (ENCRYPTED_KEY BLOB NOT NULL, ENCRYPTED_PAYLOAD BLOB NOT NULL, NONCE BLOB NOT NULL, SENDER BLOB NOT NULL, TIMESTAMP NUMBER(19), HASH BLOB NOT NULL, PRIMARY KEY (HASH));
CREATE TABLE PRIVACY_GROUP (ID BLOB NOT NULL, DATA BLOB NOT NULL, LOOKUP_ID BLOB, TIMESTAMP NUMBER(19), PRIMARY KEY (ID));
CREATE INDEX PRIVACY_GROUP_LOOKUPID ON PRIVACY_GROUP (LOOKUP_ID);
CREATE TABLE ST_TRANSACTION (ID NUMBER(19) NOT NULL, PAYLOAD_CODEC VARCHAR NOT NULL, HASH VARCHAR NOT NULL, PAYLOAD BLOB, PRIVACY_MODE NUMBER(10), TIMESTAMP NUMBER(19), VALIDATION_STAGE NUMBER(19), PRIMARY KEY (ID));
CREATE INDEX ST_TRANSACTION_VALSTG ON ST_TRANSACTION (VALIDATION_STAGE);
CREATE INDEX ST_TRANSACTION_HASH ON ST_TRANSACTION (HASH);
CREATE TABLE ST_AFFECTED_TRANSACTION (ID NUMBER(19) NOT NULL, AFFECTED_HASH VARCHAR NOT NULL, TXN_ID NUMBER(19) NOT NULL, PRIMARY KEY (ID));
