info:
  title: Tessera API reference
  description: |
    Tessera exposes several independent server APIs that are configured at startup:

    * quorum-to-tessera
    * peer-to-peer
    * third-party

    Depending on the configuration of the node, not all server APIs may be available.
  version: latest
tags:
  - name: quorum-to-tessera
    description: Operations for Quorum clients
  - name: peer-to-peer
    description: Operations for Tessera clients
  - name: third-party
    description: Operations for third party clients (for example external tools)