name: Java CI with Gradle

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

env:     
  MAVEN_REPO_CACHE_KEY: ${{ github.run_id }}-maven-${{ github.run_number }}-${{ github.run_number }}-${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test -x dependencyCheckAnalyze
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ env.MAVEN_REPO_CACHE_KEY }}
        restore-keys: |
          ${{ env.MAVEN_REPO_CACHE_KEY }}
  
  checkdependencies: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
  
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ env.MAVEN_REPO_CACHE_KEY }}
        restore-keys: |
          ${{ env.MAVEN_REPO_CACHE_KEY }}
    - uses: actions/setup-java@v1
      with:
       java-version: 11
    - run: ./gradlew dependencyCheckAnalyze -x test
       
  test: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ env.MAVEN_REPO_CACHE_KEY }}
        restore-keys: |
          ${{ env.MAVEN_REPO_CACHE_KEY }}
    - uses: actions/setup-java@v1
      with:
       java-version: 11
    - run: ./gradlew test -x dependencyCheckAnalyze  -x :tests:acceptance-test:test
  itest: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ env.MAVEN_REPO_CACHE_KEY }}
        restore-keys: |
          ${{ env.MAVEN_REPO_CACHE_KEY }}
    - uses: actions/setup-java@v1
      with:
       java-version: 11
    - run: ./gradlew :tests:acceptance-test:test
      
  atest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ env.MAVEN_REPO_CACHE_KEY }}
          restore-keys: |
            ${{ env.MAVEN_REPO_CACHE_KEY }}
      - run: |
          ./gradlew build -x test -x dependencyCheckAnalyze -x javadoc
          export TESSERA_JAR=`ls $(pwd)/tessera-dist/tessera-app/build/libs/tessera-app-*-app.jar`
          cd
          git clone https://github.com/jpmorganchase/quorum-examples.git
          git clone https://github.com/jpmorganchase/quorum-acceptance-tests.git
          echo "Install geth"
          curl -L https://dl.bintray.com/quorumengineering/quorum/v2.5.0/geth_v2.5.0_linux_amd64.tar.gz -o geth.tar.gz
          tar xvzf geth.tar.gz
          sudo mv geth /usr/local/bin/
          geth version
          echo "Installed geth"
          echo "Install solc"
          curl -L https://github.com/ethereum/solidity/releases/download/v0.5.4/solc-static-linux -o solc
          sudo mv solc /usr/local/bin/
          sudo chmod 755 /usr/local/bin/solc
          solc --version
          echo "Installed solc"
          echo "Install gauge"
          curl -L https://github.com/getgauge/gauge/releases/download/v1.0.7/gauge-1.0.7-linux.x86_64.zip -o gauge.zip
          sudo unzip -o gauge.zip -d /usr/local/bin
          cd quorum-acceptance-tests
          gauge install
          cd
          echo "Installed gauge"
          echo "Start $TESSERA_JAR for 7 nodes"
          cd quorum-examples/examples/7nodes
          ./tessera-init.sh
          ./init.sh istanbul
          ./start.sh istanbul tessera
          cd ../../../
          echo "Started $TESSERA_JAR for 7 nodes"
          echo "Run quorum-acceptance-tests"
          cd quorum-acceptance-tests
          cp config/application-local.7nodes.yml config/application-local.yml
          mvn test
          echo "Complete quorum-acceptance-tests"
        env:
          MAVEN_OPTS: -Xms1024m -Xmx2048m
